language: scala

env:
  matrix:
    # The lastest Haxe, disabled due to https://github.com/HaxeFoundation/haxe/issues/4369
    # - HAXE_FILE=haxe_latest.tar.gz
    # Haxe 3.2.0
    - HAXE_FILE=haxe_2015-05-12_master_77d171b.tar.gz

scala:
  - 2.11.2

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

before_install:
 - travis_retry sudo add-apt-repository ppa:eyecreate/haxe -y
 - travis_retry sudo apt-get update -qq
 - travis_retry sudo apt-get install -qq neko ocaml mono-devel 
 - travis_retry wget http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/linux64/"$HAXE_FILE"
 - sudo tar zxvf "$HAXE_FILE"
 - sudo mv haxe-* haxe
 - export PATH=$PATH:`pwd`/haxe
 - export HAXE_STD_PATH=`pwd`/haxe/std
 - travis_retry haxelib setup .haxelib
 - travis_retry haxelib install nodejs
 - travis_retry haxelib install continuation
 - travis_retry haxelib install hxjava
 - travis_retry haxelib install hxcs
 - travis_retry haxelib git hxparse https://github.com/Simn/hxparse.git bb0da70a409f3e29baef5f5d91d8c4a148c4df85
 - travis_retry haxelib git haxeparser https://github.com/Simn/haxeparser.git 317838b23f2f8a54e68fe6afabc099dc914d4856
 - travis_retry haxelib git HUGS https://github.com/qifun/HUGS.git
